// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYy_qvHYZX1qVCOZpIg-aO-daurUX6OjU',
    appId: '1:1057415870183:web:ff1ffbca0827914fb25442',
    messagingSenderId: '1057415870183',
    projectId: 'todo-application-86c08',
    authDomain: 'todo-application-86c08.firebaseapp.com',
    storageBucket: 'todo-application-86c08.appspot.com',
    measurementId: 'G-W1K3RDSGXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeekMSOga8K76_ZJgI6E3MX7hA1yPW2MM',
    appId: '1:1057415870183:android:95e125103a485b5eb25442',
    messagingSenderId: '1057415870183',
    projectId: 'todo-application-86c08',
    storageBucket: 'todo-application-86c08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqin4gP5-fuR0W-axpNxaFK36QGCt9-os',
    appId: '1:1057415870183:ios:caf86aa459faa035b25442',
    messagingSenderId: '1057415870183',
    projectId: 'todo-application-86c08',
    storageBucket: 'todo-application-86c08.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqin4gP5-fuR0W-axpNxaFK36QGCt9-os',
    appId: '1:1057415870183:ios:3e8c131ab12ae28fb25442',
    messagingSenderId: '1057415870183',
    projectId: 'todo-application-86c08',
    storageBucket: 'todo-application-86c08.appspot.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
